###################  项目启动端口  ###################
logback:
  file:
    #日志存放路径
    dir: c:/logs/easy_trans_test/
easy-trans:
  autotrans:
    package: com.fhs.test.service.**
  is-enable-redis: false
spring:
  redis:
    host: 192.168.0.213
    port: 6379
    password: 123456
    database: 0
    timeout: 6000